### PR TITLE
App Bar Remodel

### PR DESCRIPTION
**Pull request by calebwebster**
### Overview

This PR will modify the existing top app bar/tool bar to give a shiny new look and create some extra space on our `SingleWeatherReportActivity` page.

AndroidManifest.xml was changed to assign the `NoActionBar` style to `SingleWeatherReportActivity`. Then a `com.google.android.material.appbar.AppBarLayout` was added to `activity_single_weather_report.xml` and the blue top bar copied in.

Layout weights and such shenanigans were all sorted out and now it looks great!

### Changes Since Created

- Fixed bug that made weather state section of SingleWeatherReportActivity hidden.

This PR closes issue #35

### CODE REVIEW

**Review by HarperThurlow — APPROVED** [review]
Bar look's alot slicker with the back button intergrated into it. I think we should have this for our entire application if thats possible. Can bring it up in our next meeting and implement your code everywhere.

**Review by JackMcGill — CHANGES_REQUESTED** [review]
The new appBar looks great, good job @CalebWebsterJCU. 
However when running the code on my machine, the `SingleWeatherReportActivity` has some missing items/broken UI.
#### Before the changes in this PR:
Screen Shot 2021-10-22 at 7 56 23 pm


#### After the changes in this PR:
Screen Shot 2021-10-22 at 7 51 56 pm

Specifically the changes made to the appBar have resulted in the date view being moved above the temperature, and we no longer get the weather state image and text. The spacing around the text and icons at the bottom looks a little different as well. At first glance, it appears that by removing the appBar you have caused the layout weights to not work properly. Before we merge this code in, could you see if you can fix the problem @CalebWebsterJCU?

**Comment by calebwebster** [comment]
Fixed.

**Review by JackMcGill — COMMENTED** [review]
Good work

**Pull request merged**
