### PR TITLE
Re-implement local database

### LINKED ISSUE #15: Improve the local database
Exactly what the title says. Currently, the local database that was implemented in #5 is a little bit overcomplicated for what we need. The code is all from a tutorial, and needs major refactoring before it can be used properly in our app.  Completing this issue should re-implement the local database, in a simpler way that is ready to be used with the rest of our app straight out of the box.

### Tasks

- [x] Remove old database code
- [x] Solve #10 so that `WeatherReportModel` objects can be passed between activities
- [x] Develop new local database 
- [x] Code to write to database
- [x] Code to read from database
- [x] Update documentation

### PR DESCRIPTION
**Pull request by JackMcGill**
# Overview
## What's being introduced
This PR replaces the old local database code, with a simpler implementation of the Room SQLite database. See the [database documentation](https://github.com/JackMcKill/CP3407-Project/blob/develop/Documentation/Database.md) page for a detailed explanation of what is happening under the hood.

This PR introduces code to:

- Write to the database
- Read from the database and display the results in an interactive recyclerView. Currently just a single line (the ID of the weather report) is displayed

After this PR is merged, there is still some work to do to provide complete functionality, however as I've been working on this issue for 2 weeks now I think it's best to just merge it and move onto something else. The remaining functionality of:

- Deleting entries from the database
- Making the recyclerView items rich in content (currently they just display an ID number).

can be implemented later in another Sprint.

## Notes
This branch was merged a couple of commits ago in #21 in order to give the rest of the team access to the newly created `Documentation` folder.
Closes #15

### CODE REVIEW

**Comment by JackMcGill** [comment]
Commit 97619dd is just resolving merge conflicts that were introduced in #29. Once you have checked this over, we can do a "squash and merge" @HarperThurlow.

**Comment by HarperThurlow** [comment]
Hey @JackMcKill,

Just got myself set up for holidays and installing Android Studio on my laptop. Will have my review back to you by tomorrow :)

**Review by HarperThurlow — CHANGES_REQUESTED** [review]
For me the buttons don't show when I am in the Database Prototype activity. I get a very big grey box (which I am guessing is the recycler view). Might need something to say Recycler view is x and y big and then make it scrollable with the buttons underneath it so it shows your add and delete buttons. Maybe in the meeting this afternoon we can go over it together (as I might be doing something wrong too)?

**Comment by JackMcGill** [comment]
> For me the buttons don't show when I am in the Database Prototype activity. I get a very big grey box. 

I would say it's because your local database is empty. You are correct, the big grey box is where the `recyclerView` goes, but as your is empty there is nothing for it to show.

1. First use the `APIactivity` to search for a location. Then click on one of the list items to see this view:
Screen Shot 2021-09-29 at 10 10 42 am

2. Press `ADD TO LOCAL DATABASE` 
3. Go back to the `recyclerView` and you should see your entry has been added:
Screen Shot 2021-09-29 at 10 13 36 am
(notice that the ID numbers in both my screenshots match - a new entry has been added).

**Review by HarperThurlow — APPROVED** [review]
Ahh gotcha. Ok all good. I see your TODO list too but lets focus on that in sprint two 👍

**Pull request merged**
