### PR TITLE
Improve local database

### LINKED ISSUE #10: Make WeatherDataModel a Parcelable object by implementing the Parecelable interface.
We need a way to pass a `weatherReportModel` object to another activity inside an intent. Intents can only carry Primitive data types, we can't just pass it an object. Currently, the only way we can pass a `weatherReportModel` to another activity would be to pass each property separately, then rebuild the pieces into a new `weatherReportModel` in the new activity, which would look something like this:  

**Inside the first activity**
```java
Intent intent = new Intent(CurrentActivity.this, NewActivity.class);

intent.putExtra("weather_id", singleWeatherReport.getId());
intent.putExtra("weather_state_name", singleWeatherReport.getWeather_state_name());
intent.putExtra("weather_state_abbr", singleWeatherReport.getWeather_state_abbr());
intent.putExtra("wind_direction_compass", singleWeatherReport.getWind_direction_compass());
intent.putExtra("created", singleWeatherReport.getCreated());
intent.putExtra("applicable_date", singleWeatherReport.getApplicable_date());
intent.putExtra("the_temp", singleWeatherReport.getThe_temp());
// for all remaining properties etc etc...

startActivity(intent);
```

**Inside the new activity**
```java
WeatherReportModel weatherReportModel = new WeatherReportModel();

weatherReportModel.setId(intent.getLongExtra("weather_id", 0); // a default value of 0 
weatherReportModel.setWeather_state_name(intent.getStringExtra("weather_state_name");
weatherReportModel.setWeather_state_abbr(intent.getStringExtra("weather_state_abbr");
// for all remaining properties etc etc...
```

By implementing the `Parcelable` interface, it will mean we can pass a `weatherReportModel` directly into the intent, and just retrieve it directly on the other side in the second activity. There is some extra boilerplate code that must be implemented, but it shouldn't be too difficult. It might be easier to re-write the `WeatherReportModel` class from scratch.

Here are some resources to help get started:
- [A related StackOverflow post](https://stackoverflow.com/questions/7181526/how-can-i-make-my-custom-objects-parcelable)
- [The official Android documentation](https://developer.android.com/reference/android/os/Parcelable)

### LINKED ISSUE #15: Improve the local database
Exactly what the title says. Currently, the local database that was implemented in #5 is a little bit overcomplicated for what we need. The code is all from a tutorial, and needs major refactoring before it can be used properly in our app.  Completing this issue should re-implement the local database, in a simpler way that is ready to be used with the rest of our app straight out of the box.

### Tasks

- [x] Remove old database code
- [x] Solve #10 so that `WeatherReportModel` objects can be passed between activities
- [x] Develop new local database 
- [x] Code to write to database
- [x] Code to read from database
- [x] Update documentation

### PR DESCRIPTION
**Pull request by JackMcGill**
This PR will merge new, simplified code for our local database. It is almost finished, there are just a few TODO items left to complete.

### CODE REVIEW

**Comment by HarperThurlow** [comment]
Hey Jack, I am pretty slammed today and tomorrow but on Tuesday I will review this code to double check everything is ok. This shouldn't block you from doing any work.

**Comment by JackMcGill** [comment]
> Hey Jack, I am pretty slammed today and tomorrow but on Tuesday I will review this code to double check everything is ok. This shouldn't block you from doing any work.

@HarperThurlow 
All good, I should have what I'm working on finished by then. I'll update you once it's ready.

**Review by HarperThurlow — CHANGES_REQUESTED** [review]
Couple of notes:
- You currently have 2 different naming conventions happening within your file. Your TextViews are maxTempView and your maximum tempreature is max_temp. In our contributing.md file we say we are using camelCase so we need to find a consistant way to display these.
- I see you have written the a TODO "convert this model into a Room Entity. Avoids confusion between this class and the WeatherReport class". I will be using the WeatherReport model for the external database stuff so I am not sure how this will work between them but will need to sort it out.

**Comment by JackMcGill** [comment]
@HarperThurlow 
Correct, thanks for spotting the incorrect naming in the `WeatherReportModel`. All those exisiting names are remnants from when I copied the code over from the metaweather json object, I completely forgot about them. I'll refactor, and those changes will be pushed when I push the rest of my work on this branch. Currently adding in functionality to delete and view the data stored inside the database.

The TODO "convert this model into a Room Entity...." has been resolved, see latest commit. Basically, rather than having our exisiting `WeatherReportModel` and then another `WeatherReport`, they have been combined together, and `WeatherReportModel` gains the Room annotations. Those annotations don't impact it's functionality, they are just there so that Room knows what to use as an entity, so it will work with your external database code no worries.

**Pull request merged**
